preemptable: true
restartable: true  # if not using shuriken, the job will restart with from a new checkpoint

#environmentVars:
#  - PWD=/eai

resources:
  mem: 12
  cpu: 8
  gpu: 1

data:
  - eai.lizard_muffin.orlando:/output:rw
  - eai.lizard_muffin.data@latest:/data:rw
  - eai.baal.xai_caps_shr:/share:rw

command:
#  - bash
#  - /workspace/fast-influence-functions/scripts/run_MNLI.sh
  - python
  - /workspace/fast-influence-functions/create_index.py 
